version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - dotnet restore
      - dotnet build --configuration Release
      - dotnet lambda deploy-function GloboClimaApi --region us-east-1
